ENGR00292415 fix mx6sl_evk screenshot not work issue
screenshot not work on mx6sl_evk, root cause is screenshot
implementation on KitKat use FBO it need OpenGL ES2.0 API,
mx6sl_evk does not have GPU 3D core so it can't support,
has to use old screenshot implementation on mx6sl_evk.

screenshot not work issue on mx6sl_evk.
Root cause is some API change on Lollipop, NO_FBO_SCREENSHOT should
do the same kind of change.

Reorder the member variable initialization to align with its definition
pass the build with -Werror,-Wold-style-cast -Wsign-conversion

The build error for SL, SX, and 7D as below:
SurfaceFlinger.cpp:874:28: error: code will never be executed [-Werror,-Wunreachable-code]
SurfaceFlinger.cpp:3374:77: error: unused parameter 'rotation' [-Werror,-Wunused-parameter]

This commit merge with below commits:
49533e4 MA-5877 fix screenshot not work issue on mx6sl_evk.
93182d4 MA-7158 Fix compile error for mm6.0(part).
2822702 MA-6972 Fix the build error for native in m-preview(part).

Change-Id: Ib2feaa5ed99bfef04c74e9ef5e3fde5e861cf184
Signed-off-by: Richard Liu <r66033@freescale.com>
Signed-off-by: guoyin.chen <guoyin.chen@freescale.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/374
Reviewed-by: Xuegang Liu <xuegang.liu@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/906